# Generated by Django 3.2.18 on 2023-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230330_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
