# Generated by Django 3.2.19 on 2023-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230504_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pass_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
